//
// Created by Filip on 12/04/2025.
//

#ifndef PROJEKT_1_PROGRAMOWANIE_OBIEKTOWE_HOGWEEDOFPINE_H
#define PROJEKT_1_PROGRAMOWANIE_OBIEKTOWE_HOGWEEDOFPINE_H


#include "../Plant.h"

class HogweedOfPine : public Plant {

};


#endif //PROJEKT_1_PROGRAMOWANIE_OBIEKTOWE_HOGWEEDOFPINE_H
