//
// Created by Filip on 12/04/2025.
//

#ifndef PROJEKT_1_PROGRAMOWANIE_OBIEKTOWE_NIGHTSHADEBERRIES_H
#define PROJEKT_1_PROGRAMOWANIE_OBIEKTOWE_NIGHTSHADEBERRIES_H


#include "../Plant.h"

class NightshadeBerries : public Plant {

};


#endif //PROJEKT_1_PROGRAMOWANIE_OBIEKTOWE_NIGHTSHADEBERRIES_H
